"""Pydantic models for registry metadata and entries."""

from typing import Any

from pydantic import BaseModel, Field


class RegistryMetadata(BaseModel):
    """
    User-provided metadata for a registered function.

    This model captures the metadata that users provide via the @register
    decorator. All fields are validated using Pydantic.

    Attributes:
        title: Human-readable title for the function
        description: Detailed description of what the function does
        tags: Optional list of categorization tags (e.g., ["io", "database"])
        deprecated: Whether this function is deprecated (default: False)
        deprecation_message: Optional message explaining the deprecation and
            suggesting alternatives

    Examples:
        Basic metadata:

        >>> metadata = RegistryMetadata(
        ...     title="Calculate Mean",
        ...     description="Calculate arithmetic mean of values"
        ... )
        >>> metadata.title
        'Calculate Mean'
        >>> metadata.tags
        []
        >>> metadata.deprecated
        False

        With all fields:

        >>> metadata = RegistryMetadata(
        ...     title="Load CSV",
        ...     description="Load CSV file",
        ...     tags=["io", "legacy"],
        ...     deprecated=True,
        ...     deprecation_message="Use load_parquet instead"
        ... )
        >>> metadata.deprecated
        True
        >>> metadata.deprecation_message
        'Use load_parquet instead'
    """

    title: str = Field(..., description="Human-readable title for the function")
    description: str = Field(..., description="Detailed description of what the function does")
    tags: list[str] = Field(default_factory=list, description="Optional categorization tags")
    deprecated: bool = Field(default=False, description="Whether this function is deprecated")
    deprecation_message: str | None = Field(
        default=None, description="Message explaining deprecation"
    )


class RegistryEntry(BaseModel):
    """
    Complete registry entry for a registered function.

    This model represents a complete entry in the global registry, combining
    user-provided metadata with auto-detected information and the generated
    JSON schema.

    Attributes:
        metadata: User-provided metadata from @register decorator
        module_path: Full module path where the function is defined
        function_name: Name of the function (from __qualname__)
        json_schema: JSON schema generated by Pydantic TypeAdapter

    Examples:
        Creating a registry entry:

        >>> from wt_registry.models import RegistryMetadata, RegistryEntry
        >>> metadata = RegistryMetadata(
        ...     title="Add Numbers",
        ...     description="Add two integers"
        ... )
        >>> entry = RegistryEntry(
        ...     metadata=metadata,
        ...     module_path="myapp.math",
        ...     function_name="add",
        ...     json_schema={"type": "object", "properties": {}}
        ... )
        >>> entry.fully_qualified_name
        'myapp.math.add'
        >>> entry.import_statement
        'from myapp.math import add'
    """

    metadata: RegistryMetadata = Field(..., description="User-provided metadata")
    module_path: str = Field(..., description="Full module path (e.g., 'mypackage.tasks')")
    function_name: str = Field(..., description="Function name (e.g., 'calculate_mean')")
    json_schema: dict[str, Any] = Field(..., description="JSON schema from pydantic TypeAdapter")

    @property
    def fully_qualified_name(self) -> str:
        """
        Generate fully qualified name: 'module_path.function_name'.

        Returns:
            The fully qualified name of the function

        Examples:
            >>> metadata = RegistryMetadata(title="Test", description="Test function")
            >>> entry = RegistryEntry(
            ...     metadata=metadata,
            ...     module_path="myapp.tasks",
            ...     function_name="process_data",
            ...     json_schema={}
            ... )
            >>> entry.fully_qualified_name
            'myapp.tasks.process_data'
        """
        return f"{self.module_path}.{self.function_name}"

    @property
    def import_statement(self) -> str:
        """
        Generate import statement: 'from module_path import function_name'.

        Returns:
            A Python import statement for this function

        Examples:
            >>> metadata = RegistryMetadata(title="Test", description="Test function")
            >>> entry = RegistryEntry(
            ...     metadata=metadata,
            ...     module_path="myapp.tasks",
            ...     function_name="process_data",
            ...     json_schema={}
            ... )
            >>> entry.import_statement
            'from myapp.tasks import process_data'
        """
        return f"from {self.module_path} import {self.function_name}"
